# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shardus
email: info@shardus.com
description: > # this means to ignore newlines until "baseurl:"
  Shardus is building distributed ledger software to remedy the problems of traditional blockchains â€” scalability, decentralization and efficiency. 
  The technology being developed will use compute and state sharding to accommodate billions of daily active users, allowing for global-scale decentralized networks. 
  The Shardeum and Liberdus networks will be launched using this technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shardus.com" # the base hostname & protocol for your site
thumbnail: "assets/img/shardus-thumb-04-2019-1-91.png"
thmnl_width: 1200
thmnl_height: 627

# Build settings
markdown: kramdown
exclude: []
